export const TEXTS = {
  ru: {
    headerT: 'Создание депозита',
    yourNameT: 'Ваше имя',
    yourNamePlaceholderT: 'Напишите имя',
    selectCurrencyT: 'Выберите валюту',
    cashT: 'Наличные',
    cryptoT: 'Криптовалюта',
    investmentAmountT: 'Сумма инвестиции',
    enterAmountT: 'введите сумму',
    minDepositT: 'минимальный депозит',
    investmentPeriodT: 'Срок инвестиции',
    monthsT: 'мес',
    riskPercentT: 'Процент риска',
    doneT: 'Готово',
    fillAllFieldsT: 'Заполните все поля',
    errorT: 'Что-то пошло не так',
    // DepositRqstDone
    requestAcceptedT: 'Запрос на создание портфеля принят!',
    waitConfirmT: 'Ожидайте подтверждение от администратора',
    sendToAddressT: 'Отправьте',
    toAddressT: 'на адрес',
    goToAccountT: 'Перейти в личный кабинет',
    copyAddressT: 'Скопировать адрес',
    addressCopiedT: 'Адрес скопирован в буфер обмена',
  },

  de: {
    headerT: 'Einzahlung erstellen',
    yourNameT: 'Ihr Name',
    yourNamePlaceholderT: 'Name eingeben',
    selectCurrencyT: 'Währung wählen',
    cashT: 'Bargeld',
    cryptoT: 'Kryptowährung',
    investmentAmountT: 'Investitionsbetrag',
    enterAmountT: 'Betrag eingeben',
    minDepositT: 'Mindesteinzahlung',
    investmentPeriodT: 'Anlagezeitraum',
    monthsT: 'Mon.',
    riskPercentT: 'Risikoprozent',
    doneT: 'Fertig',
    fillAllFieldsT: 'Bitte alle Felder ausfüllen',
    errorT: 'Etwas ist schiefgelaufen',
    // DepositRqstDone
    requestAcceptedT: 'Antrag auf Portfolioerstellung angenommen!',
    waitConfirmT: 'Warten Sie auf die Bestätigung des Administrators',
    sendToAddressT: 'Senden Sie',
    toAddressT: 'an die Adresse',
    goToAccountT: 'Zum persönlichen Konto',
    copyAddressT: 'Adresse kopieren',
    addressCopiedT: 'Adresse in die Zwischenablage kopiert',
  },
};
