export const TEXTS = {
  ru: {
    portfolioNotFoundT: 'Портфель не найден',
    portfolioInfoT: 'Информация по портфелю',
    initialPriceT: 'Цена портфеля начальная',
    currentPriceT: 'Цена портфеля текущая',
    portfolioProfitT: 'Прибыль по портфелю',
    weekT: 'Неделя',
    noWeekDataT: 'Нет данных по неделям',
    refundHistoryT: 'Пополнения портфеля:',
    totalInitialPriceT: 'Цена портфеля после пополнения',
    refundDepositT: 'Пополнение депозита',
    backT: 'Назад',
    // IndexPage
    yourPortfoliosT: 'Ваши портфели',
    noPortfoliosT: 'У вас еще нет подтвержденных портфелей',
    portfolioT: 'Портфель',
    endDateT: 'дата окончания',
    detailsT: 'Подробнее',
  },

  de: {
    portfolioNotFoundT: 'Portfolio nicht gefunden',
    portfolioInfoT: 'Portfolio-Informationen',
    initialPriceT: 'Anfangswert des Portfolios',
    currentPriceT: 'Aktueller Portfoliowert',
    portfolioProfitT: 'Portfolio-Gewinn',
    weekT: 'Woche',
    noWeekDataT: 'Keine Wochendaten',
    refundHistoryT: 'Portfolio-Aufstockungen:',
    totalInitialPriceT: 'Portfoliopreis nach Aufstockung',
    refundDepositT: 'Einzahlung',
    backT: 'Zurück',
    // IndexPage
    yourPortfoliosT: 'Ihre Portfolios',
    noPortfoliosT: 'Sie haben noch keine bestätigten Portfolios',
    portfolioT: 'Portfolio',
    endDateT: 'Enddatum',
    detailsT: 'Details',
  },
};
