export const TEXTS = {
  ru: {
    portfolioNotFoundT: 'Портфель не найден',
    portfolioInfoT: 'Информация по портфелю',
    initialPriceT: 'Цена портфеля начальная',
    currentPriceT: 'Цена портфеля текущая',
    portfolioProfitT: 'Прибыль по портфелю',
    weekT: 'Неделя',
    noWeekDataT: 'Нет данных по неделям',
    refundHistoryT: 'Пополнения портфеля:',
    totalInitialPriceT: 'Цена после пополнения',
    refundDepositT: 'Пополнение',
    backT: 'Назад',
    // IndexPage
    yourPortfoliosT: 'Ваши портфели',
    noPortfoliosT: 'У вас еще нет подтвержденных портфелей',
    portfolioT: 'Портфель',
    endDateT: 'дата окончания',
    detailsT: 'Подробнее',
    endsInDaysT: 'заканчивается через',
    daysT: 'дней',
    portfolioEndsInT: 'Портфель заканчивается через',
    possibleActionsT: 'Возможные действия:',
    withdrawAllT: 'Забрать всю сумму',
    withdrawPartT: 'Забрать часть суммы',
    extendYearT: 'Продлить ещё на год',
    requestSentT: 'Заявка отправлена администратору',
    whichCurrencyT: 'В какой валюте?',
    cashT: 'Наличные',
    cryptoT: 'Криптовалюта',
    selectCryptoT: 'Выберите криптовалюту:',
    howMuchWithdrawT: 'Сколько хотите вывести',
    amountInT: 'Сумма в',
    doneT: 'Готово',
    amountExceedsT: 'сумма выше цены портфеля',
    maxT: 'максимум',
    portfolioClosedT: 'портфель закрыт',
  },

  de: {
    portfolioNotFoundT: 'Portfolio nicht gefunden',
    portfolioInfoT: 'Portfolio-Informationen',
    initialPriceT: 'Anfangswert des Portfolios',
    currentPriceT: 'Aktueller Portfoliowert',
    portfolioProfitT: 'Portfolio-Gewinn',
    weekT: 'Woche',
    noWeekDataT: 'Keine Wochendaten',
    refundHistoryT: 'Portfolio-Aufstockungen:',
    totalInitialPriceT: 'Portfoliopreis nach Aufstockung',
    refundDepositT: 'Einzahlung',
    backT: 'Zurück',
    // IndexPage
    yourPortfoliosT: 'Ihre Portfolios',
    noPortfoliosT: 'Sie haben noch keine bestätigten Portfolios',
    portfolioT: 'Portfolio',
    endDateT: 'Enddatum',
    detailsT: 'Details',
    endsInDaysT: 'endet in',
    daysT: 'Tagen',
    portfolioEndsInT: 'Portfolio endet in',
    possibleActionsT: 'Mögliche Aktionen:',
    withdrawAllT: 'Gesamtbetrag abheben',
    withdrawPartT: 'Teilbetrag abheben',
    extendYearT: 'Um ein Jahr verlängern',
    requestSentT: 'Antrag wurde an den Administrator gesendet',
    whichCurrencyT: 'In welcher Währung?',
    cashT: 'Bargeld',
    cryptoT: 'Kryptowährung',
    selectCryptoT: 'Kryptowährung auswählen:',
    howMuchWithdrawT: 'Wie viel möchten Sie abheben',
    amountInT: 'Betrag in',
    doneT: 'Fertig',
    amountExceedsT: 'Betrag übersteigt den Portfoliowert',
    maxT: 'maximal',
    portfolioClosedT: 'Portfolio geschlossen',
  },
};
